# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: debian:sid-slim

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt update
  - apt -y install hugo

pages:
  script:
  - rm -rvf resources public
  - hugo
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
