# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: hugomods/hugo:debian-nightly

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production

# before_script:
#   - apt update
#   - apt -y install hugo
test:
  stage: test
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  script:
    - hugo

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - hugo
  artifacts:
    paths:
      - public
