baseURL = "https://wiki.luebeck.freifunk.net"
languageCode = "de-de"
title = "FFHL Wiki"
theme = "hugo-book"


[params]
BookRepo = "https://git.chaotikum.org/freifunk-luebeck/ffhl-wiki"
BookEditPath = "_edit/master/content"
BookLogo = "/logo.svg"
BookSection = "docs"
BookComments = true
BookPortableLinks = true
#BookMenuBundle = "/menu"
